### ISSUE TITLE
Hindi translation doesnt work properly

### ISSUE THREAD

**Issue by Kaito-Kiddo** [ONLYOFFICE/plugin-translator#59]
Kindly check Attached PIC
<img width="530" alt="onlyoffice translate wrong" src="https://user-images.githubusercontent.com/48343906/149886917-49f9245c-9067-4d27-bf28-35651eab2b3e.png">

I tried translating and inserting 
" Hello "
 but it didnt inserted नमस्ते

**Comment by ShockwaveNN** [comment]
Hi, could you clarify

This is an incorrect word or is it is a correct word but inserted incorrectly?
Because translations provided by Google Translate and we have no ability to change it and judging by your screenshot - word from Google Translate at left sidebar looks same as inserted in document

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
